apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KavinduGeesara/argo-voyage.git
    targetRevision: main
    path: k8s/hello-app
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-app
  syncPolicy:
    automated:
      prune: true       # delete anything removed from Git
      selfHeal: true     # revert manual kubectl edits back to Git's version
    syncOptions:
      - CreateNamespace=true